const { migrate } = require("drizzle-orm/node-postgres/migrator");
const { db, pool } = require("./db");
const path = require("path");

async function runMigrations() {
  if (process.env.DB_MOCK === "true") {
    console.log("DB_MOCK is true. Physical migrations skipped.");
    return;
  }
  console.log("Running migrations...");
  try {
    // Target the migration folder generated by drizzle-kit
    await migrate(db, { migrationsFolder: path.join(__dirname, "../../drizzle") });
    console.log("Migrations ran successfully!");
  } catch (error) {
    console.error("Migration failed:", error);
    process.exit(1);
  } finally {
    // Close pool connection after migrations complete
    await pool.end();
  }
}

runMigrations();
